name: ci

on: push

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-${{ hashFiles('bun.lockb') }}

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Set up project
        run: bun i

      - name: Run linters
        run: bun run lint

      - name: Run tests
        run: bun run test
